let times = [
    {   esporte : "Basquetebol",
        time : "R10 Score Vasco",
        descricao : "O R10 Score Vasco da Gama é o time de basquete profissional do Vasco da Gama, um dos maiores clubes de futebol do Brasil. A equipe, que leva o nome do craque Ronaldinho Gaúcho (R10), compete em diversas competições nacionais e busca consolidar sua presença no cenário do basquete brasileiro.",
        link: "https://www.youtube.com/watch?v=Nt_KobqfZ6k",
        tags: "basket basquete r10 tim duncan campeoes",
        link2: "index2.html"
        
    },
    {
        esporte: "Futebol",
        time : "Clube de Regatas Vasco da Gama",
        descricao: "um dos clubes mais tradicionais e populares do Brasil, com uma rica história que transcende o futebol. Fundado em 1898, o Vasco é conhecido como o 'Gigante da Colina' e possui uma torcida apaixonada e numerosa.",
        link: "https://vasco.com.br/conteudo/1924-a-resposta-historica/#:~:text=O%20Vasco%20da%20Gama%20foi,à%20tão%20almejada%20grandeza%20esportiva.",
        tags: "futebol CRVG Vascão trem bala da colina ",
        link2: "index3.html"
    },
    {   esporte : "Os craques",
        time : "Dinamite e os maiorais",
        descricao : "Roberto Dinamite é, sem sombra de dúvida, o maior ídolo da história do Vasco da Gama. Nascido em Duque de Caxias, Rio de Janeiro, em 13 de abril de 1954, ele se tornou uma lenda viva do futebol brasileiro. Veja os outros que o acompanham nessa lista!!",
        link: "https://www.youtube.com/watch?v=I-lUPygkv4Q",
        tags: "idolos maiorais dinamite queixada lenda rio de janeiro",
        link2: "https://ge.globo.com/futebol/times/vasco/noticia/dinamite-e-indiscutivelmente-o-maior-idolo-do-vasco-listamos-10-craques-que-fizeram-historia-no-clube-vote.ghtml"
        
    },
    
];

let idolos= [{
    alcunha: "é ele",
    tags:"vascao",
    link3:"index3.html"
}
]
let jogadoresFutebol = [
    {
        time: "Clube de Regatas Vasco da Gama",
        numero:"1",
        nome:"Léo Jardim",
        posicao:"Goleiro",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/leo-jardim/",
    },
    {  
        time:"Clube de Regatas Vasco da Gama",
        numero:"13",
        nome:"Keiller da Silva Nunes",
        posicao:"Goleiro",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/keiller/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"37",
        nome:"Pablo de Paula Cardoso",
        posicao:"Goleiro",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/pablo/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"40",
        nome:"Phillipe Gabriel Pires de Oliveira",
        posicao:"Goleiro",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/phillipe-gabriel/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"2",
        nome:"José Luis Rodríguez Bebanz",
        posicao:"Lateral-Direito",
        nacionalidade:"Uruguai",
        linkjogador: "https://vasco.com.br/elenco/puma-rodriguez/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"32",
        nome:"Robert Samuel Rojas Chávez",
        posicao:"Lateral-Direito",
        nacionalidade:"Paraguai",
        linkjogador: "https://vasco.com.br/elenco/roberto-rojas/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"96",
        nome:"Paulo Henrique de Oliveira Alves",
        posicao:"Lateral-Direito",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/paulo-henrique/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"3",
        nome:"Leonardo Pinheiro da Conceição",
        posicao:"Zagueiro",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/leo/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"4",
        nome:"Maicon Pereira Roque",
        posicao:"Zagueiro",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/maicon/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"38",
        nome:"João Victor da Silva Marcelino",
        posicao:"Zagueiro",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/joao-victor/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"33",
        nome:"Lyncon Correa Gonçalves",
        posicao:"Zagueiro",
        nacionalidade:"Brasil",
        linkjogador: "https://netvasco.com.br/futebol/jogadores/538-lyncon.shtml",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"44",
        nome:"Luiz Gustavo",
        posicao:"Zagueiro",
        nacionalidade:"Brasil",
        linkjogador: "https://www.sofascore.com/pt/jogador/gustavo-luiz/1634148",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"6",
        nome:"Lucas Piton",
        posicao:"Lateral-Esquerdo",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/lucas-piton/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"12",
        nome:"Victor Luis Chuab Zamblauskas",
        posicao:"Lateral-Esquerdo",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/victor-luis/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"66",
        nome:"Leandro Vianna da Silva Gama",
        posicao:"Lateral-Esquerdo",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/leandrinho/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"20",
        nome:"Juan Sebastián Sforza",
        posicao:"Volante",
        nacionalidade:"Argentina",
        linkjogador: "https://vasco.com.br/elenco/sforza/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"5",
        nome:"Josef de Souza Dias",
        posicao:"Volante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/souza/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"25",
        nome:"Hugo Moura Arruda da Silva",
        posicao:"Volante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/hugo-moura/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"58",
        nome:"Lucas Eduardo de Souza Oliveira",
        posicao:"Volante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/lucas-eduardo/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"85",
        nome:"Mateus Carvalho dos Santos",
        posicao:"Volante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/mateus-carvalho/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"11",
        nome:"Philippe Coutinho Correia",
        posicao:"Meio-Campista",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/philippe-coutinho/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"14",
        nome:"Guilherme Estrella de Paiva",
        posicao:"Meio-Campista",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/estrella/",
    },

    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"8",
        nome:"Jair Rodrigues Júnior",
        posicao:"Meio-Campista",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/jair/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"10",
        nome:"Dimitri Payet",
        posicao:"Meio-Campista",
        nacionalidade:"França",
        linkjogador: "https://vasco.com.br/elenco/dimitri-payet/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"18",
        nome:"Paulo Lucas Santos de Paula",
        posicao:"Meio-Campista",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/paulinho-2/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"27",
        nome:"Pablo Ignacio Galdames Millán",
        posicao:"Meio-Campista",
        nacionalidade:"Chile",
        linkjogador: "https://vasco.com.br/elenco/pablo-galdames/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"98",
        nome:"João Pedro Murilo de Paula Morais",
        posicao:"Meio-Campista",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/jp/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"21",
        nome:"Jean David Meneses Villarroel",
        posicao:"Atacante",
        nacionalidade:"Chile",
        linkjogador: "https://vasco.com.br/elenco/jean-david/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"90",
        nome:"Alex Teixeira Santos",
        posicao:"Atacante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/alex-teixeira/",
    },

    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"17",
        nome:"Emerson Rodríguez",
        posicao:"Atacante",
        nacionalidade:"Colômbia",
        linkjogador: "https://www.sofascore.com/pt/jogador/emerson-rodriguez/1082956",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"7",
        nome:"David Corrêa da Fonseca",
        posicao:"Atacante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/david/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"28",
        nome:"Adson Ferreira Soares",
        posicao:"Atacante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/adson/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"31",
        nome:"Rossicley Pereira da Silva",
        posicao:"Atacante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/rossi/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"77",
        nome:"Rayan Vitor Simplicio Costa",
        posicao:"Atacante",
        nacionalidade:"Brasil",
        linkjogador: "https://vasco.com.br/elenco/rayan/",
    },
    {
        time:"Clube de Regatas Vasco da Gama",
        numero:"99",
        nome:"Pablo Ezequiel Vegetti Pfaffen",
        posicao:"Atacante",
        nacionalidade:"Argentina",
        linkjogador: "https://vasco.com.br/elenco/vegetti/",
    },
 
];

let jogadoresBasquete = [
    {
        time:"R10 Score Vasco",
        numero:"21",
        nome:"Serjão Conceição",
        posicao:"Pivô",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/serjao-73309",
    },
    {
        time:"R10 Score Vasco",
        numero:"7",
        nome:"Tarek Santana",
        posicao:"Pivô",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/tarek-143706",
    },
    {
        time:"R10 Score Vasco",
        numero:"4",
        nome:"Alexsander Ale",
        posicao:"Armador",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/ale-143705",
    },
    {
        time:"R10 Score Vasco",
        numero:"1",
        nome:"Gustavo Basilio",
        altura:"",
        posicao:"Armador",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/gustavo-basilio-73529",
    },
    {
        time:"R10 Score Vasco",
        numero:"9",
        nome:"Lucas Santos",
        posicao:"Armador",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/lucas-santos-143700",
    },
    {
        time:"R10 Score Vasco",
        numero:"8",
        nome:"Cauê Freitas",
        posicao:"Armador",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/caue-verzola-73822",
    },
    {
        time:"R10 Score Vasco",
        numero:"19",
        nome:"Humberto Luiz Gomes Gomes",
        posicao:"Armador",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/humberto-73395",
    },
    {
        time:"R10 Score Vasco",
        numero:"11",
        nome:"Vieira Marquinhos",
        posicao:"Ala",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/marquinhos-69960",
    },
    {
        time:"R10 Score Vasco",
        numero:"13",
        nome:"Rafael Paulichi",
        posicao:"Ala",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/rafael-paulichi-104499",
    },
    {
        time:"R10 Score Vasco",
        numero:"10",
        nome:"Fabricio Russo",
        posicao:"Ala",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/fabricio-russo-73809",
    },
    {
        time:"R10 Score Vasco",
        numero:"29",
        nome:"Matheus Weber",
        posicao:"Ala",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/matheus-weber-143708",
    },
    {
        time:"R10 Score Vasco",
        numero:"6",
        nome:"Matheus Eugeniusz",
        posicao:"Armador",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/matheus-eugeniusz-73303",
    }, {
        time:"R10 Score Vasco",
        numero:"12",
        nome:"Thiago Mathias",
        posicao:"Ala",
        nacionalidade:"Brasil",
        linkjogadorBasquete: "https://www.365scores.com/pt-br/basketball/player/thiago-mathias-73825",
    },
];
